---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

--------------------------------

This is a line added by Keegan

This is a line added by Simeon from RStudio

This is a line added by Nick from RStudio

Simeon: It went smoothly and we had no problems with anything involving Git or RStudio.

Keegan: I've already used Git before, but adding the repository to RStudio was very simple. Then committing/pushing was also seamless.

Nick: I got everything set up pretty easy

I didn't wind up running into any errors in class- I already had git and RStudio set up earlier this week, but I did have some small trouble finding the UI options for git within RStudio.

After class I messed around with this file a bit more after class and knitted to the .md per specs and got some conflicts when committing. Git mostly seemed to do a good enough job of selecting sections to add or delete so it really didn't need much from me - except for the one where I needed to pull before pushing and I wound up having to revert something but I didn't have to redo any work somehow. (I'm not exactly sure what went on there.) 

While doing this I also ran into the issue that Github doesn't automatically update my email when committing, so I now own several commits under my non-school account (FancyEveryDay) but fixed it for the last couple commits.
